spring.application.name=vedorajewelry
spring.datasource.url=jdbc:mysql://localhost:3306/vedora
spring.datasource.username=root
spring.datasource.password=tadtn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true